### ISSUE TITLE
Rate limiters

### ISSUE THREAD

**Issue by OnlyLogiicC** [hugzenfeu/lokavoile-backend-strapi#10]
Te renseigner sur ce que sont des rate limiters et les implémenter soit au niveau de nginx soit au niveau de strapi.

**Comment by hugzenfeu** [comment]
ajouté sur strapi-dev avec une limite globale à 10 Mo de mémoire pour toutes les applications et 30 requîtes par seconde par IP je sais pas si c'est bien ?

**Comment by hugzenfeu** [comment]
je me dis que comme le front en fera beaucoup 30 c'est deja pas énorme non ?
sinon je peux le mettre en white list le front

**Comment by OnlyLogiicC** [comment]
Oui, c'est une bonne idée de mettre en whute list le serveur front.

**Comment by hugzenfeu** [comment]
tu as son IP ou ca peut changer ?

**Comment by OnlyLogiicC** [comment]
Je sais pas trop. Je vais regarder. Mais je me dis peut-être que si un golem fait trop de requête en passant par le front, faudrait pas que ça passe parce que c'est en white list. Donc peut-être juste laisser à 30 en général.
