### ISSUE TITLE
ajouter thumbnail à boat

### ISSUE THREAD

**Issue by hugzenfeu** [hugzenfeu/lokavoile-backend-strapi#4]

**Comment by OnlyLogiicC** [comment]
FInalement, comme une image est convertie en plusieurs format dont le format `thumbnail`, peut-être qu'il n'est pas necessaire de rajouter ce champ. On se dit que c'est la première image qui est affichée et point barre. En plus, ce sera plus simple pour Lokavoile. Ils n'auront pas à se soucier de downscale une image pour opti la thumbnail, c'est strapi qui le fait direct.

**Comment by hugzenfeu** [comment]
Ok vendu
