### ISSUE TITLE
ajouter le champ slug à Boat, News, Blog

### ISSUE THREAD

**Issue by OnlyLogiicC** [hugzenfeu/lokavoile-backend-strapi#5]
Ajouter le champ slug aux models suivants :
- Boat ;
- News ;
- Blog ;

Je crois qu'il y a un type spécial dans Strapi pour générer un slug automatiquement basé sur certains champ du model. Je crois que Strapi comprend ensuite que c'est donc unique.
Si possible, générer un endpoint de format `/<model>/slug/{slug}` pour pouvoir implémenter la fonction `findBySlug`. A défaut, on utilisera un filtre sur l'enpoint get générique.

**Comment by hugzenfeu** [comment]
changements fait sur strapi-dev

**Comment by hugzenfeu** [comment]
je cloture et tu en recréera un si besoin
